-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) AS SALES
FROM PRODUCT AS p
INNER JOIN OFFLINE_SALE AS os 
ON p.PRODUCT_ID = os.PRODUCT_ID
GROUP BY PRODUCT_CODE	
ORDER BY SALES DESC, PRODUCT_CODE